restruct travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -16,10 +16,10 @@ matrix:
         - python: 2.7
           env: LATEST="true" TENSORFLOW="true" COVERAGE="false"
 install:
-  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
-      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
+  - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
+        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
     else
-      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
+        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
     fi
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
@@ -27,26 +27,30 @@ install:
   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - conda info -a
-  - if [[ "$LATEST" == "true" ]]; then
-      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas sklearn;
+  - if [[ "${LATEST}" == "true" ]]; then echo "test";
     else
-      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib=$MATPLOTLIB_VERSION pandas=$PANDAS_VERSION sklearn=$SKLEARN_VERSION;
+    echo "notest";
+    fi
+  - if [[ "${LATEST}" == "true" ]]; then
+        conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas sklearn;
+    else
+        conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib=$MATPLOTLIB_VERSION pandas=$PANDAS_VERSION sklearn=$SKLEARN_VERSION;
     fi
   - source activate test-environment
-  - if [[ "$COVERAGE" == "true" ]]; then pip install coverage coveralls
-  - if [[ "$TENSORFLOW" == "true" ]]; then
-      python -c "import tensorflow; print('tensorflow %s' % tensorflow.__version__)";
+  - if [[ "${COVERAGE}" == "true" ]]; then pip install coverage coveralls
+  - if [[ "${TENSORFLOW}" == "true" ]]; then
+        python -c "import tensorflow; print('tensorflow %s' % tensorflow.__version__)";
     else
-      python -c "import sklearn; print('sklearn %s' % sklearn.__version__)";
-      python -c "import pandas; print('pandas %s' % pandas.__version__)";
-      python -c "import matplotlib; print('matplotlib %s' % matplotlib.__version__)";
+        python -c "import sklearn; print('sklearn %s' % sklearn.__version__)";
+        python -c "import pandas; print('pandas %s' % pandas.__version__)";
+        python -c "import matplotlib; print('matplotlib %s' % matplotlib.__version__)";
     fi
 script: bash ./ci/.travis_test.sh
 after_success:
-    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
+    - if [[ "${COVERAGE}" == "true" ]]; then coveralls || echo "failed"; fi
 notifications:
-  email:
-    recipients:
-      - mail@sebastianraschka.com
+    email:
+      recipients:
+          - mail@sebastianraschka.com
     on_success: always
     on_failure: always
